### ISSUE TITLE
Update to Swift 5

### ISSUE THREAD

**Issue by unnamedd** [Evolution-App/iOS#118]

**Comment by Kalvin126** [comment]
Any update on this?

**Comment by unnamedd** [comment]
Hi @Kalvin126, 

unfortunately some libraries I use broke the API, which make the update to Swift 5 a little bit more complicated than I thought, for this reason, I have two news for you here: 

The sad one: the current version won't have any update anymore.
The good one: I'm working on the new version of the app, and this new version will be completely fresh and new. 

I'm still researching some things that I will bring to the app and as soon I restart the development, you will be able to see here if you watch the repo.

**Comment by Kalvin126** [comment]
Alrighty. I was hoping to contribute if you are open to that. Any time lines on the next version?

**Comment by unnamedd** [comment]
Not yet, but I'm going to organize better the Projects and the code will be open since the very beginning, then you will be able to send some PRs, which will help a lot!
