### ISSUE TITLE
Scrolling the Proposals Table some times registers as a select

### ISSUE THREAD

**Issue by Kalvin126** [Evolution-App/iOS#121]
### Checklist

- [x] I have searched [existing issues](https://github.com/evolution-app/ios/issues) and this is not a duplicate

### Information

iPhone XS, iOS 13.1.2 

- App Version: 1.2 (11)
- Steps to reproduce bug: 
    - repeatedly scroll the table
- What happened?
    - The screen pushes to proposal detail page of where I initially executed a swipe gesture
- What should have happened?
    - The table should keep scrolling

I can't really reproduce on the simulator when building this project though

**Comment by unnamedd** [comment]
Unfortunately, as the project isn't being updated for more than one year, it won't be updated anymore, but replaced by a new and fresh version. 

In any case, thank you for your time to create this issue @Kalvin126.
