### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by fishcharlie** [Evolution-App/iOS#123]
What needs to be done to get a new release published for this? Would love to help out so we can get some of the latest features like dark mode in the store.

**Comment by unnamedd** [comment]
Hei @fishcharlie,
thanks for your issue, but please, before we continue take a minute and read my answer here for a similar question. It should explain you a little bit about the inactivity of the project for now: https://github.com/Evolution-App/iOS/issues/40#issuecomment-593797505
