### ISSUE TITLE
Implement support to Push Notification

### ISSUE THREAD

**Issue by unnamedd** [Evolution-App/iOS#68]
We need to have the *Feeder* component working well to start this issue.

Push Notifications
- Proposal creation
- Proposal status changes

Checklist
- [x] Register device
- [x] Receive notification
- [x] Track notification

_**Feeder** is a CLI component responsible to get details from proposals and store the informations into a database, which will be used by our backend component._

**Comment by bguidolim** [comment]
What kind of push notifications the user will receive?
Do we have any push config implemented on server side?
